apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
spec:
  nodeName: 'ip-192-168-25-30.eu-west-1.compute.internal'
  containers:
  - name: hello-world
    image: psk8s.azurecr.io/hello-app:1.0
    ports:
    - containerPort: 8080