apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: fs-0d224492c2b75a83d.efs.eu-west-1.amazonaws.com
    path: "/"
