apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world-pod
spec:
  containers:
  - name: hello-world-pod
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector:
    nodegroup: lkt-temp-09
