apiVersion: v1
kind: Pod
metadata:
  name: hello-app
spec:
  restartPolicy: Always  # Place it here at the pod level
  containers:
    - name: hello-container
      image: alpine:latest
      command: ["sh", "-c", "while true; do echo 'Hello, World!'; sleep 5; done"]
